automatic: False # Autonoumous hitting

time_to_wait : 3.0 # time to stay in REST mode (where both robots are in REST, includes returning to position)
# MUST be longer than time_object_record in recorder_properties (to record properly)

safety_distance: 0.80 # object distance for which to PAUSE the robots when running autonomously

fixed_flux: True # Whether to use a fixed flux for each hit (otherwise uses file below in a loop)
desired_fluxes_filename: "high_fluxes.txt" # This file MUSt be in 'desired_hitting_fluxes' folder


iiwa7:
  
  hitting_flux : 1.2

  return_position:
    x: 0.55
    y: -0.05
    z: 0.35 # config 1 :0.22

  hit_direction:
    x: 0
    y: 1 
    z: 0

  object_offset:
    x : 0.0 #0.02 0.04
    y : -0.11 #-0.15
    z : 0.05 # config 1: -0.06 # -0.05 #-0.12 #-0.05
  
  # position to go to before hiting, relative to object center + object_offset
  placement_offset:  
    x : 0.00
    y : -0.25 # config 1: -0.25 
    z : 0.0


iiwa14:

  hitting_flux : 1.2
  
  return_position:
    x: 0.55 
    y: 0.05
    z: 0.25

  hit_direction:
    x: 0
    y: -1 
    z: 0
    
  object_offset:
    x : 0.00 # 0.05 0.04
    y : 0.10 #0.015 # exact IRL is .13
    z : -0.05 # -0.05 #-0.10 #-0.07

  placement_offset: 
    x : 0.00
    y : 0.3
    z : 0.0

