options:
  filter_gain: 0.2

control:
    iiwa1:
      dsGainPos: 6.0
      lambda0Pos: 200.0
      lambda1Pos: 200.0 
      dsGainOri: 3.0
      lambda0Ori: 20.0
      lambda1Ori: 20.0
    iiwa2:
      dsGainPos: 6.0
      lambda0Pos: 200.0
      lambda1Pos: 200.0 
      dsGainOri: 3.0
      lambda0Ori: 20.0
      lambda1Ori: 20.0
      
target:
    iiwa1:
      pos: [0.55, -0.2, 0.4]
      quat: [0.707, -0.707, 0.0, 0.0]
    iiwa2:
      pos: [0.55, 0.2, 0.4]
      quat: [-0.707, -0.707, 0.0, 0.0]

inertia:
    iiwa1:
      null_gains: [5.0, 80.0, 10.0, 30.0, 5.0, 2.0 ,2.0]
      gain: 0.001
      desired : 5.0
      direction : [0.0, 1.0, 0.0] # must be the same as the direction of hit_direction of AirHockey
      null_pos : [-0.48, 1.04,  0.02, -1.35, -1.92, -1.81, -0.81]
    iiwa2:
      null_gains: [5.0, 80.0, 10.0, 30.0, 5.0, 2.0 ,2.0]
      gain: 0.001
      desired : 5.0
      direction :  [0.0, -1.0, 0.0] # must be the same as the direction of hit_direction of AirHockey
      null_pos : [0.563, 1.166, -0.134, -1.366, -1.095, 1.763, -0.591]