use_rqt: False # set to True to use rqt reconfigure 

control:
    iiwa1:
      dsGainPos: 1.8 #4.5 #8.0  # Used on desidred vel ONLY when receiving a desired Pose 
      lambda0Pos: 120 # 100 # config 1: 120 #     #70.0 #80.0
      lambda1Pos: 70 # config 1: 80 #   ##35.0 40.0
      alphaPos: 50 # 50 ##150.0  # gain on desired vel during hit (too high from lam0 makes it deviate)
      lambda0PosHit: 40 # lambda 0 used during hit
      dsGainOri: 1.0 #2.5 #3.0
      lambda0Ori: 10.0 # 6.0 #5.0
      lambda1Ori: 5.0 # 3.0 #2.5
      alphaOri: 10.0
      ImpedanceOriStiffness: [50, 50, 42] # [260,260,100] # Task space gains in x,y,z  
      ImpedanceOriDamping: [2.5, 2.5, 2.5] ## [3,3.4,1.6]
      ImpedancePosStiffness: [1800.0, 1800.0, 2000.0]
      ImpedancePosDamping: [43.3, 31.68, 37.19]
    iiwa2:
      dsGainPos: 1.8 #1.3 #1.5 # 2.5
      lambda0Pos: 120 #120 # 90 #100.0
      lambda1Pos: 30 #60 # 30 #50.0 (lower than 30 to avoid oscillations when hitting) IMPROVE THIS ONE??
      alphaPos: 50 #70 #150.0
      lambda0PosHit: 40 #50 # lambda 0 used during hit
      dsGainOri: 1.0
      lambda0Ori: 8.0 #10.0
      lambda1Ori: 4.0 # 5.0
      alphaOri: 10.0
      ImpedanceOriStiffness: [42, 42, 50] #[70.0, 70.0, 70.0]
      ImpedanceOriDamping: [2.5, 2.5, 2.5] #[2.7, 2.3, 2.7] # UNTESTED used to be 3 3 2.7
      ImpedancePosStiffness: [1500.0, 1500.0, 1800.0] #[500.0, 500.0, 500.0] #[1800.0, 1800.0, 2000.0]
      ImpedancePosDamping: [40.3, 40.68, 40.19] #[10.0, 10.0, 10.0] # 

target:
    iiwa1:
      pos: [0.55, -0.05, 0.22] 
      quat: [0.707, -0.707, 0.0, 0.0] 
      null_pos: [-0.48, 1.04,  0.02, -1.35, -1.92, -1.81, -0.81] # config 1: [-0.48, 1.04,  0.02, -1.35, -1.92, -1.81, -0.81] ## config 2 : [-1.125, 1.530, 1.193, -1.399, -2.819, -1.306, -0.355]
    iiwa2:
      pos: [0.55, 0.05, 0.22]
      quat: [0.5, 0.5, -0.5, 0.5] #[0.707, 0.707, 0.0, 0.0]  #[-0.707, -0.707, 0.0, 0.0]
      null_pos : [0.561, 1.193, -0.148, -1.296, -1.075, 1.836, -0.639] # config 2 : [0.524, 0.753, 0-0.199, -1.464, 0.136, 0.999, 1.849]

inertia:
    iiwa1:
      null_stiffness: [50.0, 300.0, 40.0, 50.0, 15.0, 10.0, 10.0] # [5.0, 80.0, 10.0, 30.0, 5.0, 2.0 ,1.0] # # 
      null_damping: [5.0, 12.0, 5.0, 5.0, 2.0, 3.0 ,1.0] 
      gain: 1.0 #1.0 #0.001
      desired : 5.0
      direction : [0.0, 1.0, 0.0] # must be the same as the direction of hit_direction of AirHockey
    iiwa2:
      null_stiffness: [50.0, 200.0, 40.0, 50.0, 15.0, 10.0, 10.0] #[50.0, 120.0, 10.0, 40.0, 0.1, 0.001, 5.0] ##[10.0, 70.0, 0.00, 10.0, 0.00, 0.00, 1.0] # [5.0, 80.0, 10.0, 30.0, 5.0, 2.0 ,1.0] # # 
      null_damping: [5.0, 12.0, 5.0, 5.0, 2.0, 1.0 ,1.0] 
      gain: 1.0 #0.001 #1.0 #0.5 #0.001100.0
      desired : 5.0
      direction :  [0.0, -1.0, 0.0] # must be the same as the direction of hit_direction of AirHockey

start: # PD gains for starting phase 
    iiwa1:
      stiffness: [110., 60.5, 60.5, 33., 20.625, 10.7375, 6.75] # 4.7375, 2.75
      damping: [18.75, 22.5, 18.75, 22.5 , 6., 1.0, 0.6 ] #0.6, 0.3 ]
    iiwa2:
      stiffness: [150.0, 90.0, 80.0, 50.0, 20.5, 6.25, 4.5]
      damping: [22.0, 20.0, 15.0, 12.0, 5.0, 1.1 , 0.8]